version: '3.4'

services:
  ordersapi:
    image: ${DOCKER_REGISTRY-}ordersapi
    ports:
      - 6060:6060
    environment:
        ASPNETCORE_URLS: http://+:6060
        MongoDB__ConnectionString: mongodb://root:example@host.docker.internal:27017/
        MongoDB__Database: Orders
        PORT: 6060
        CLIENT_ORIGIN_URL: http://localhost:4040
        AUTH0_AUDIENCE: https://orders.example.com
        AUTH0_DOMAIN: dev-hloe0m6fbmv25qkt.us.auth0.com
        TEST_MODE: false
    build:
      context: OrdersAPI
      dockerfile: Dockerfile    

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
